version: '3.2'
services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      volumes:
        - ./config/definitions.json:/etc/rabbitmq/definitions.json
        - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      environment:
          RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      ports:
          - 5672:5672
          - 15672:15672

    bill_postgres:
      image: postgres:alpine
      container_name: bill_postgres
      volumes:
        - ./config/bill_init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
          POSTGRES_PASSWORD: fred
          POSTGRES_DB: bill_db
      ports:
          - 5432:5432

    logistic_postgres:
      image: postgres:alpine
      container_name: logistic_postgres
      volumes:
        - ./config/logistic_init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
          POSTGRES_PASSWORD: fred
          POSTGRES_DB: logistic_db
      ports:
          - 5434:5432

    checkout:
      depends_on:
      - rabbitmq
      build:
        context: ./checkout
        dockerfile: Dockerfile
      ports: 
        - 8080:8080

    bill:
      depends_on:
      - rabbitmq
      - bill_postgres
      build:
        context: ./bill
        dockerfile: Dockerfile
      ports: 
        - 9090:9090


    logistic:
      depends_on:
      - rabbitmq
      - logistic_postgres
      build:
        context: ./logistic
        dockerfile: Dockerfile
      ports: 
        - 7070:8080